### ISSUE TITLE
When running configure missing miscperl.pl on Ubuntu 18.04

### ISSUE THREAD

**Issue by gnud** [jserv/tvision#3]
Running `./configure` yields the following error:

> Can't locate miscperl.pl in @INC (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at config.pl line 8. 

A workaround I used:
`export PERL5LIB=.`

Now running `./configure` completes with success.

**Comment by jserv** [comment]
This repository is obsolete, please check https://github.com/magiblot/tvision
for better GNU/Linux support.
